config/routes.rb
Carlife::Application.routes.draw do

  get "api/parts/:id" => "vehicles#get_vehicle_parts"
  get "api/popular/:brand" => "vehicles#get_popular_models"
  get "api/vehicle/:user_id" => "client#get_vehicles"

  post "/products/search" => "products#search"

  post "/addmantencion/:vehicle_id" => "maintenances#create"

  post "getpartinfo" => "maintenances#getpartinfo"

  get "getparts" => "maintenances#getparts"

  post "maintenances/create_issue" => "maintenance_issues#create"

  resources :maintenance_issues

  resources :maintenances

  get "clients/new"=>"client#new"
  get "suppliers/new"=>"supplier#new"
  get "clients/edit" => "client#edit"  
  get "clients/:id" => "client#index", as: "client_home"
  get "clients/:id" => "client#index", as: "client"
  get "clients/:id/:vehicle" => "client#index", as: "client_home_vehicle"  
  put "clients/:id" => "client#update"
  get "suppliers/:id" => "supplier#index", as: "supplier_home"
  get "messages" => "messages#index", as: "messages"
  post "messages/create" => "messages#create_history"
  post "messages/compose" => "messages#create_compose"

  get "logout" => "home#logout"
  post "signup/fb" => "client#create_fb"
  post "login/fb" => "home#do_login_fb"
  get "login" => "home#show_login"
  get "login" => "home#show_login"
  post "do_login" => "home#do_login"
  get "admin"=> "home#admin"
  post "clients"=>"client#create"
  post "suppliers"=>"supplier#create"
  get "tests"=>"home#test"
  get "image-search/v1"=>"home#test"
  get "event/delete/:id"=>"events#destroy"
  get "products/delete/:id"=>"products#destroy"
  get "products/edit/:id"=>"products#edit"
  post "vehicles/load-models" => "vehicles#load_models"

  get "quienes_somos" => "home#quienes_somos"
  get "faq" => "home#faq"

  resources :users
  resources :models
  resources :vehicles
  resources :events
  resources :products
  resources :categories
  resources :parts
  resources :news

  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def index

    @user = current_user
    @other_news = News.all.sort_by {|m| m.date}.reverse[0..3]
    @news = @other_news.first
    @other_news.delete(@news)
    @product = Product.all.sample
    @events= Event.all.sort_by(&:created_at).reverse[0..8]


  end


  def logout
    session[:user_id] = nil
    redirect_to root_path
  end


  def show_login
    render "login"
  end

  def do_login

    ok = false
    email = params[:email]
    pass = params[:password]

    user = nil

    if User.exists?(:email => email)
      user = User.find_by_email(email)
      if user.password == pass
        ok = true
      else
      @warning = "Error: Contrasena Incorrecta!"
      end
    else
      @warning = "Error: Email de Usuario No Registrado!"
    end

    if ok
      session[:user_id] = user.id

      if user.type=="Admin"
           redirect_to "/admin"
           return
      else

      if user.type=="Supplier"
          redirect_to "/suppliers/"+user.id.to_s
          return
      end


      redirect_to root_path
      end


    else

    render "login"
    end
  end


  def do_login_fb

    fbemail = params[:username]+"@facebook.com"

    if !Client.exists?(:email => fbemail)
      render :js => "login_unexisting"
      return
    end


    user = User.find_by_email(fbemail)
    session[:user_id] = user.id
    render :js => "login_accepted"


  end

  def admin

    @user=current_user


      if @user == nil
      then
        redirect_to root_path
        return
      end

      if @user.type==nil
        then
        redirect_to root_path
        return
      end

       if @user.type!="Admin"
       then
         redirect_to root_path
         return
       end

  end

  def quienes_somos
  end

  def faq
  end


  def test
    @user = current_user
    @o1 = owns_vehicle(1)
    @o8 = owns_vehicle(8)
    @o52 = owns_vehicle(52)
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<table border="0">

  <td valign="top" width="200">
    </div>
    <div id="columns">
      <div id="side">
        <ul>
          <li><a href="http://localhost:3000">Home</a></li>
          <li><a href="http://www..../faq">Questions</a></li>
          <li><a href="http://www..../news">News</a></li>
          <li><a href="http://www..../contact">Contact</a></li>






        </ul>
      </div>

  </td>

  <td>
    <div id="main">


            <h1>Esta es la pagina de administrador...</h1>

      <li><a href=models>Administrar modelos de autos</a></li>
      <%link_to "Administrar modelos de autos", models_path%>
      <li><a href=categories>Administrar categorias de los productos y servicios de los proveedores</a></li>
      <%link_to "Administrar categorias de los productos y servicios de los proveedores", categories_path%>


  </td>

  </p></p>
</table>

app/views/home/faq.html.erb
<div style="width:800px;">

<h1>Preguntas Frecuentes (FAQ)</h1>

  <br>
<h2>¿A quién va dirigido Carlife?</h2>
Esta dirigido a dos segmentos: Proveedores  y Usuarios propiamente tal.  En Proveedores se consideran empresas del rubro automotriz, proveedoras de toda clase de
productos y servicios para automóviles.  Por el otro lado están los Conductores: usuarios de la aplicación que consideran a toda persona que tenga un vehículo.

<h2>¿Para que les sirve a los usuarios?</h2>
  A toda persona que tenga un (o más!) vehículo, Carlife le brina una plataforma donde puede hacer seguimiento del estado
  de sus componentes, además de interactuar con otros usuarios que tengan vehículos similares, y conocer productos y servicios disponibles para su auto.
  Además permite llevar un seguimiento de los eventos asociados al auto, y de los costos que se ha incurrido.


  <h2>¿Para que les sirve a los proveedores?</h2>
  Para todas las empresas de productos y servicios automotrices, Carlife es la vitrina perfecta donde mostrarse a miles
  de potenciales clientes en el país.  Aquí podrán publicar sus productos y ofertas y estar a la mano de quienes las necesitarán


  <h2>¿Cuanto cuesta ingresar a Carlife?</h2>
  Es absolutamente gratis!

  <h2>¿Cómo gana dinero Carlife?</h2>
  De ninguna forma.  Somos bastante giles y trabajamos gratis.

</div>
<br>
<br>
<%= link_to 'Volver', "javascript:history.go(-1)" %>
<br>

app/views/home/index.html.erb
      <div id="home_sidebar">
        <%=render "products/bar"%>
      </div>



    <div id="home_main">


      <div id="recent_activity_box">
        <h2>Actividad Reciente:</h2>
        <% @events.each do |event| %>
            <%= render "events/feedshow", :@event => event%>
        <% end %>


      </div>


        <div id="news_box">
          <h2>NOTICIAS</h2>
          <%= link_to image_tag(@news.picture, {:id => "home_news_picture" }), news_path(@news)%>
          <h2><%=link_to @news.title, news_path(@news)%></h2>

          <table id="other news">
            <%@other_news.each do |news|%>
            <tr>
              <td>
                   <%=link_to image_tag(news.picture, :size => "86x50"), news_path(news) %>
              </td>
              <td>
                   <%= link_to news.title, news_path(news), :class => "home_other_news_title"  %>
              </td>

            </tr>

            <%end%>


          </table>


        </div>



        <div id="oferta_area">
            <h2 id="label_oferta_destacada">Oferta Destacada:</h2>
            <div id="oferta_box">
              <%=link_to image_tag(@product.picture,:id => "oferta_picture"), supplier_home_path(@product.supplier) %>
              <%= link_to @product.name,supplier_home_path(@product.supplier), :id => "oferta_name" %>
            </div>

        </div>

    </div>




<div id=home_footer>

  <%= link_to "Quienes Somos", quienes_somos_path,:class => "footer_link", :id => "quienes_somos_link"%>
  <%= link_to "FAQ", faq_path,:class => "footer_link", :id => "faq_link"%>
  <%= link_to "Contacto", "mailto:contacto@carlife.com",:class => "footer_link", :id =>"contacto_link"%>

</div>

app/views/home/login.html.erb
<script>
fb_sdk();
</script>

<%=  @warning %>


<h2>Ingresa tus datos, o 
</h2>




<%=link_to_function image_tag("fb_sign_in_small.png"),"fb_login()", {:class => "fb-login-button"}%> 




<div id="login">



  <%= form_tag(:action => "do_login") do %>
      <%= label_tag :email, "Email" %><br />
      <%= text_field_tag(:email) %>
      <p></p>
      <%= label_tag :password, "Password" %><br />
      <%= text_field_tag :password , "", :type => "password" %>
      <p></p>
      <%= submit_tag("Iniciar Sesion") %>

  <% end %>



</div>

app/views/home/quienes_somos.html.erb
<h1>Quienes Somos</h1>

<%=image_tag "qs.jpg", size: "360x270" %>

<br>
<br>
Carlife nace un emprendimiento de jóvenes con diversos interéses, pero unidos por una gran pasión por los automóviles y la tecnología.
<br>
<br>
Actualmente es propiedad de sus dos desarrolladores:
<br>
<h3>Nicolás Tomic   <%=link_to "(nitomic@uc.cl)", "mailto:nitomic@uc.cl"%>  </h3>
Ingeniero Industrial en computación Pontificia Universidad Católica de Chile, experto en Progamación Web, Ventas y Mecánica Automotríz
<br>
<h3>Felipe Balart <%=link_to "(ffbalart@uc.cl)", "mailto:ffbalart@uc.cl"%>  </h3>
Ingeniero Industrial en computación Pontificia Universidad Católica de Chile,  experto en Progamación Web, Plataformas Virtuales, Diseño y Marketing

<br>
<br>
<br>
<br>

<%= link_to 'Volver', "javascript:history.go(-1)" %>

app/views/home/test.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <title>Google Search API Sample</title>
  <script src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">

      google.load('search', '1');

      var imageSearch;

      function addPaginationLinks() {

          // To paginate search results, use the cursor function.
          var cursor = imageSearch.cursor;
          var curPage = cursor.currentPageIndex; // check what page the app is on
          var pagesDiv = document.createElement('div');
          for (var i = 0; i < cursor.pages.length; i++) {
              var page = cursor.pages[i];
              if (curPage == i) {

                  // If we are on the current page, then don't make a link.
                  var label = document.createTextNode(' ' + page.label + ' ');
                  pagesDiv.appendChild(label);
              } else {

                  // Create links to other pages using gotoPage() on the searcher.
                  var link = document.createElement('a');
                  link.href="javascript:imageSearch.gotoPage("+i+');';
                  link.innerHTML = page.label;
                  link.style.marginRight = '2px';
                  pagesDiv.appendChild(link);
              }
          }

          var contentDiv = document.getElementById('content');
          contentDiv.appendChild(pagesDiv);
      }

      function searchComplete() {

          // Check that we got results
          if (imageSearch.results && imageSearch.results.length > 0) {

              // Grab our content div, clear it.
              var contentDiv = document.getElementById('content');
              contentDiv.innerHTML = '';

              // Loop through our results, printing them to the page.
              var results = imageSearch.results;
              for (var i = 0; i < results.length; i++) {
                  // For each result write it's title and image to the screen
                  var result = results[i];
                  var imgContainer = document.createElement('div');
                  var title = document.createElement('div');

                  // We use titleNoFormatting so that no HTML tags are left in the
                  // title
                  title.innerHTML = result.titleNoFormatting;
                  var newImg = document.createElement('img');

                  // There is also a result.url property which has the escaped version
                  newImg.src=result.tbUrl;
                  imgContainer.appendChild(title);
                  imgContainer.appendChild(newImg);

                  // Put our title + image in the content
                  contentDiv.appendChild(imgContainer);
              }

              // Now add links to additional pages of search results.
              addPaginationLinks(imageSearch);
          }
      }

      function OnLoad() {

          // Create an Image Search instance.
          imageSearch = new google.search.ImageSearch();

          // Set searchComplete as the callback function when a search is
          // complete.  The imageSearch object will have results in it.
          imageSearch.setSearchCompleteCallback(this, searchComplete, null);

          // Find me a beautiful car.
          imageSearch.execute("Subaru STI");

          // Include the required Google branding
          google.search.Search.getBranding('branding');
      }
      google.setOnLoadCallback(OnLoad);
  </script>

</head>
<body style="font-family: Arial;border: 0 none;">
<div id="branding"  style="float: left;"></div><br />
<div id="content">Loading...</div>
</body>
</html>