config/routes.rb
Carlife::Application.routes.draw do

  get "api/parts/:id" => "vehicles#get_vehicle_parts"
  get "api/popular/:brand" => "vehicles#get_popular_models"
  get "api/vehicle/:user_id" => "client#get_vehicles"

  post "/products/search" => "products#search"

  post "/addmantencion/:vehicle_id" => "maintenances#create"

  post "getpartinfo" => "maintenances#getpartinfo"

  get "getparts" => "maintenances#getparts"

  post "maintenances/create_issue" => "maintenance_issues#create"

  resources :maintenance_issues

  resources :maintenances

  get "clients/new"=>"client#new"
  get "suppliers/new"=>"supplier#new"
  get "clients/edit" => "client#edit"  
  get "clients/:id" => "client#index", as: "client_home"
  get "clients/:id" => "client#index", as: "client"
  get "clients/:id/:vehicle" => "client#index", as: "client_home_vehicle"  
  put "clients/:id" => "client#update"
  get "suppliers/:id" => "supplier#index", as: "supplier_home"
  get "messages" => "messages#index", as: "messages"
  post "messages/create" => "messages#create_history"
  post "messages/compose" => "messages#create_compose"

  get "logout" => "home#logout"
  post "signup/fb" => "client#create_fb"
  post "login/fb" => "home#do_login_fb"
  get "login" => "home#show_login"
  get "login" => "home#show_login"
  post "do_login" => "home#do_login"
  get "admin"=> "home#admin"
  post "clients"=>"client#create"
  post "suppliers"=>"supplier#create"
  get "tests"=>"home#test"
  get "image-search/v1"=>"home#test"
  get "event/delete/:id"=>"events#destroy"
  get "products/delete/:id"=>"products#destroy"
  get "products/edit/:id"=>"products#edit"
  post "vehicles/load-models" => "vehicles#load_models"

  get "quienes_somos" => "home#quienes_somos"
  get "faq" => "home#faq"

  resources :users
  resources :models
  resources :vehicles
  resources :events
  resources :products
  resources :categories
  resources :parts
  resources :news

  root :to => 'home#index'
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
belongs_to :model
belongs_to :user
has_many :parts, :dependent => :delete_all
has_many :events
has_many :maintenances

  validates :color, :year, :model_id, :user_id, presence:true

  def full_name
    self.model.brand+" "+self.model.name+" "+self.year.to_s
  end

  def total_costs
    costs = 0
    self.parts.select{|pa| !pa.price.nil?}.each do |p|
      costs = costs+p.price
    end

    self.maintenances.select{|ma| !ma.price.nil?}.each do |m|
      costs = costs+m.price
    end

    return costs
  end

  def grade
     parts=Part.find_all_by_vehicle_id(self.id)
     grade=0
     parts.each do |p|
       grade=grade+p.grade
     end

     if parts.count!=0
     grade=grade/parts.count
     else grade=0
     end

     return grade
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.json
  def new

    @first = !params[:first].nil?
    @vehicle = Vehicle.new
    @modelos = Model.all
    @modelos.sort_by! {|m| m.brand}


   

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
    @modelos = Model.all
    @only = Vehicle.where(:user_id => current_user.id).size ==1
  end



  def load_models
  @models = Model.find_all_by_brand(params[:brand])
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(params[:vehicle])
    @vehicle.user =current_user



    component_types=ComponentType.all

    partes_defecto=@vehicle.model.components

    component_types.each do |c|

        pieza_existe=@vehicle.model.components.find_by_component_type_id(c.id)


        if !pieza_existe.blank?
          #Existe una pieza por defecto para este vehiculo
          part_nueva=Part.new(:component=>pieza_existe, :vehicle=>@vehicle, :grade=>5, :creation_date=>Time.now)
          part_nueva.spoil_date = part_nueva.creation_date + estimate_lifetime(part_nueva.grade).days

        else
          #No existe una pieza por defecto, hay que crearla
          pieza_existe=Component.find_by_name(c.name)

          part_nueva=Part.new(:component=>pieza_existe, :vehicle=>@vehicle, :grade=>5, :creation_date=>Time.now)
          part_nueva.spoil_date = part_nueva.creation_date + estimate_lifetime(part_nueva.grade).days

        end

        part_nueva.save

    end



    #Temporal, hasta que se implemente subir archivos:
    @vehicle.picture = "impreza.jpg"

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to client_home_path({:id =>current_user.id,  :vehicle => @vehicle})}
        format.json { render json: @vehicle, status: :created, location: @vehicle }
      else
        @modelos=Model.all
        format.html { render action: "new" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.json
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to client_home_path({:id =>current_user.id,  :vehicle => @vehicle})}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy



    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy


    respond_to do |format|
      format.html {redirect_to client_home_path(current_user.id)}

      format.json { head :no_content }
    end
  end

  def get_vehicle_parts
    @vehicle = Vehicle.find(params[:id])
    @parts=@vehicle.parts
    @parts.sort_by! {|p| p.grade}
    respond_to do |format|
      format.json { render json: @parts }
    end

  end

  def get_popular_models
       @models=Model.find_all_by_brand(params[:brand]).sort_by! {|m| Vehicle.find_all_by_model_id(m.id).count}

       @models.select! {|m| Vehicle.find_all_by_model_id(m.id).count>0}

       respond_to do |format|
         format.json { render json: @models }
       end

  end



end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<script src="https://rawgithub.com/recurser/jquery-simple-color/master/jquery.simple-color.js" type="text/javascript"></script>

<script>
jQuery(document).ready(function($) {
    $('#vehicle_color').simpleColor({
    border: "2px solid #000",
    cellWidth: 20,
    cellHeight: 20,
    boxHeight: 30,
    boxWidth: 40,
    border: '1px solid #660033',
    buttonClass: 'button',
    columns: 7,    
    livePreview: true,
            colors : [
            '000000', '993300', '333300', '000080', '333399', '333333'/*, '800000'*/, 'FF6600',
            '808000', '008000', '008080', '0000FF', '666699', '808080', 'FF0000', 'FF9900',
            '99CC00', '339966', '33CCCC', '3366FF', '800080', '999999', 'FF00FF', 'FFCC00',
            'FFFF00', '00FF00', '00FFFF', '00CCFF', '993366', 'C0C0C0', 'FF99CC', 'FFCC99',
            'FFFF99', 'CCFFFF', '99CCFF', 'FFFFFF'
        ]


      });
  
  $("#vehicle_year").val("<%=@vehicle.year%>")
  });

  
  

</script>



<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <br>

    <div class="field">
      <%= f.label "Marca:" %> <br />
      <%= collection_select( nil,"brand_select", Model.all.map {|a| a.brand}.uniq.push("-Seleccione Marca-").sort, :to_s, :to_s, {:selected => @vehicle.model.nil? ? 0 : @vehicle.model.brand   }, {:onchange => "load_models();"})%>
    </div>

    <br>
    <div class="field">
      <%= f.label "Modelo:" %><br />
      <%= f.collection_select( :model_id, @vehicle.model.nil? ? [Model.new(brand: "Seleccione Marca...")] : Model.find_all_by_brand(@vehicle.model.brand), :id, :name, {}, {:disabled => @vehicle.model.nil?})%>
    </div>

    <br>

    <div class="field">
      <%= f.label "Color:" %><br />
      <%= f.text_field :color %>
    </div>
    <br>
    <br>

    <div class="field">
      <%= f.label "Año:" %><br />
      <%= f.select :year, options_from_collection_for_select((1910..2013).to_a,:to_s,:to_s) %>
    </div>


<br>

    <div class="actions">
    <%= f.submit  (@vehicle.id ? "Actualizar" : "Crear")%>  </div>
    <br><br>

<% end %>

app/views/vehicles/_main.html.erb
<%= image_tag(@vehicle.picture, :id => "car_pic")%>

<% if @owner %>

<div id="owner_tools_box">

    <%=  link_to image_tag("add_event_button.png", :id => "add_event_button", :class => "owner_tools_button"), new_event_path({ :vehicle =>  @vehicle})%>
    <%=  link_to image_tag("edit_vehicle_button.png", :id => "edit_vehicle_button", :class => "owner_tools_button"), edit_vehicle_path(@vehicle) %>

</div>

<%end%>


<div id="events_box_area">

    <% @vehicle.events.sort_by(&:created_at).reverse.each do |event| %>
        <%= render "events/show", :@event => event%>
     <% end %>


</div>

app/views/vehicles/_parts.html.erb
<br>
<h1 style="text-decoration: underline; position: relative; left: 100px;"> Componentes de <%= @vehicle.full_name %> </h1>

<br>
<h2 style="margin-bottom:-30px;">Costos totales incurridos: <%=number_to_currency(@vehicle.total_costs, :separator => ",", :delimiter => ".", :precision => 0 )%></h2>

<%= render "parts/index",  :@parts => @vehicle.parts%>

app/views/vehicles/edit.html.erb
<h1>Editar Vehiculo</h1>

<%= render 'form' %>


<br>


<%if @only%>
    <%= link_to 'Eliminar Vehiculo', "#", :onclick => "alert('No puede quedar sin vehiculos'); self.location='/clients/'+"+@vehicle.user.id.to_s %>
    <% else %>
    <%= link_to 'Eliminar Vehiculo', @vehicle, confirm: 'Estás seguro?', method: :delete %>
    <% end %>


<br>
<br>
<%= link_to 'Cancelar', "javascript:history.go(-1)" %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <tr>
    <th>Color</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.color %></td>
    <td><%= vehicle.year %></td>
    <td><%= link_to 'Show', vehicle %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Destroy', vehicle, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/load_models.js.erb
$("#vehicle_model_id")
                .empty()
        <%@models.each do |m|%>
                .append('<option value="<%=m.id%>"><%=m.name%></option>')
        <%end%>
        .removeAttr("disabled");

app/views/vehicles/new.html.erb
<%  if @first%>
<h1>Bienvenido! Ingresa los datos de tu vehículo</h1>
    <h3>Podrás agregar más vehículos después en tu perfil</h3>
    <%  else%>
        <h1>Agregar Nuevo Vehículo</h1>
    <%  end %>
<%= render 'form' %>



<% unless @first%>
<%= link_to 'Cancelar', "javascript:history.go(-1)" %>
<% end %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Color:</b>
  <%= @vehicle.color %>
</p>

<%=@prueba %>
<p>
  <b>Year:</b>
  <%= @vehicle.year %>
</p>

<p>
  <b>Brand:</b>
  <%= @vehicle.model.brand%>
</p>

<p>
  <b>Model:</b>
  <%= @vehicle.model.name%>
</p>

<p>
  <b>Mi dueño es:</b>
  <%= @vehicle.user.id%>
</p>


<%= link_to 'Editar', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Volver a mi perfil', "/clients/"+@vehicle.user.id.to_s %>