config/routes.rb
Carlife::Application.routes.draw do

  get "api/parts/:id" => "vehicles#get_vehicle_parts"
  get "api/popular/:brand" => "vehicles#get_popular_models"
  get "api/vehicle/:user_id" => "client#get_vehicles"

  post "/products/search" => "products#search"

  post "/addmantencion/:vehicle_id" => "maintenances#create"

  post "getpartinfo" => "maintenances#getpartinfo"

  get "getparts" => "maintenances#getparts"

  post "maintenances/create_issue" => "maintenance_issues#create"

  resources :maintenance_issues

  resources :maintenances

  get "clients/new"=>"client#new"
  get "suppliers/new"=>"supplier#new"
  get "clients/edit" => "client#edit"  
  get "clients/:id" => "client#index", as: "client_home"
  get "clients/:id" => "client#index", as: "client"
  get "clients/:id/:vehicle" => "client#index", as: "client_home_vehicle"  
  put "clients/:id" => "client#update"
  get "suppliers/:id" => "supplier#index", as: "supplier_home"
  get "messages" => "messages#index", as: "messages"
  post "messages/create" => "messages#create_history"
  post "messages/compose" => "messages#create_compose"

  get "logout" => "home#logout"
  post "signup/fb" => "client#create_fb"
  post "login/fb" => "home#do_login_fb"
  get "login" => "home#show_login"
  get "login" => "home#show_login"
  post "do_login" => "home#do_login"
  get "admin"=> "home#admin"
  post "clients"=>"client#create"
  post "suppliers"=>"supplier#create"
  get "tests"=>"home#test"
  get "image-search/v1"=>"home#test"
  get "event/delete/:id"=>"events#destroy"
  get "products/delete/:id"=>"products#destroy"
  get "products/edit/:id"=>"products#edit"
  post "vehicles/load-models" => "vehicles#load_models"

  get "quienes_somos" => "home#quienes_somos"
  get "faq" => "home#faq"

  resources :users
  resources :models
  resources :vehicles
  resources :events
  resources :products
  resources :categories
  resources :parts
  resources :news

  root :to => 'home#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence:true, uniqueness: true

  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categorías disponibles</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%=category.name%></td>
    <td><%=truncate(category.description, :length => 25)
    %></td>
    <td><%= link_to 'Ver', category %></td>
    <td><%= link_to 'Editar', edit_category_path(category) %></td>
    <td><%= link_to 'Eliminar', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Crear nueva categoria', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @category.name %>
</p>
<p>
  <b>Descripcion:</b>
  <%= @category.description %>
</p>



<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>