config/routes.rb
Carlife::Application.routes.draw do

  get "api/parts/:id" => "vehicles#get_vehicle_parts"
  get "api/popular/:brand" => "vehicles#get_popular_models"
  get "api/vehicle/:user_id" => "client#get_vehicles"

  post "/products/search" => "products#search"

  post "/addmantencion/:vehicle_id" => "maintenances#create"

  post "getpartinfo" => "maintenances#getpartinfo"

  get "getparts" => "maintenances#getparts"

  post "maintenances/create_issue" => "maintenance_issues#create"

  resources :maintenance_issues

  resources :maintenances

  get "clients/new"=>"client#new"
  get "suppliers/new"=>"supplier#new"
  get "clients/edit" => "client#edit"  
  get "clients/:id" => "client#index", as: "client_home"
  get "clients/:id" => "client#index", as: "client"
  get "clients/:id/:vehicle" => "client#index", as: "client_home_vehicle"  
  put "clients/:id" => "client#update"
  get "suppliers/:id" => "supplier#index", as: "supplier_home"
  get "messages" => "messages#index", as: "messages"
  post "messages/create" => "messages#create_history"
  post "messages/compose" => "messages#create_compose"

  get "logout" => "home#logout"
  post "signup/fb" => "client#create_fb"
  post "login/fb" => "home#do_login_fb"
  get "login" => "home#show_login"
  get "login" => "home#show_login"
  post "do_login" => "home#do_login"
  get "admin"=> "home#admin"
  post "clients"=>"client#create"
  post "suppliers"=>"supplier#create"
  get "tests"=>"home#test"
  get "image-search/v1"=>"home#test"
  get "event/delete/:id"=>"events#destroy"
  get "products/delete/:id"=>"products#destroy"
  get "products/edit/:id"=>"products#edit"
  post "vehicles/load-models" => "vehicles#load_models"

  get "quienes_somos" => "home#quienes_somos"
  get "faq" => "home#faq"

  resources :users
  resources :models
  resources :vehicles
  resources :events
  resources :products
  resources :categories
  resources :parts
  resources :news

  root :to => 'home#index'
end

app/models/maintenance_issue.rb
class MaintenanceIssue < ActiveRecord::Base

  belongs_to :maintenance
  belongs_to :part

end

app/controllers/maintenance_issues_controller.rb
class MaintenanceIssuesController < ApplicationController
  # GET /maintenance_issues
  # GET /maintenance_issues.json
  def index
    @maintenance_issues = MaintenanceIssue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @maintenance_issues }
    end
  end

  # GET /maintenance_issues/1
  # GET /maintenance_issues/1.json
  def show
    @maintenance_issue = MaintenanceIssue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @maintenance_issue }
    end
  end

  # GET /maintenance_issues/new
  # GET /maintenance_issues/new.json
  def new
    @maintenance_issue = MaintenanceIssue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @maintenance_issue }
    end
  end

  # GET /maintenance_issues/1/edit
  def edit
    @maintenance_issue = MaintenanceIssue.find(params[:id])
  end

  # POST /maintenance_issues
  # POST /maintenance_issues.json
  def create
    @maintenance_issue = MaintenanceIssue.new(params[:maintenance_issue])

    respond_to do |format|
      if @maintenance_issue.save
        format.html { redirect_to @maintenance_issue, notice: 'Maintenance issue was successfully created.' }
        format.js
        format.json { render json: @maintenance_issue, status: :created, location: @maintenance_issue }
      else
        format.html { render action: "new" }
        format.json { render json: @maintenance_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /maintenance_issues/1
  # PUT /maintenance_issues/1.json
  def update
    @maintenance_issue = MaintenanceIssue.find(params[:id])

    respond_to do |format|
      if @maintenance_issue.update_attributes(params[:maintenance_issue])
        format.html { redirect_to @maintenance_issue, notice: 'Maintenance issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @maintenance_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenance_issues/1
  # DELETE /maintenance_issues/1.json
  def destroy
    @maintenance_issue = MaintenanceIssue.find(params[:id])
    @maintenance_issue.destroy

    respond_to do |format|
      format.html { redirect_to maintenance_issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/maintenance_issues_helper.rb
module MaintenanceIssuesHelper
end

app/views/maintenance_issues/_form.html.erb
<%= form_for(@maintenance_issue) do |f| %>
  <% if @maintenance_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maintenance_issue.errors.count, "error") %> prohibited this maintenance_issue from being saved:</h2>

      <ul>
      <% @maintenance_issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :maintenance_id %><br />
    <%= f.number_field :maintenance_id %>
  </div>
  <div class="field">
    <%= f.label :part_id %><br />
    <%= f.number_field :part_id %>
  </div>
  <div class="field">
    <%= f.label :fixed %><br />
    <%= f.check_box :fixed %>
  </div>
  <div class="field">
    <%= f.label :old_grade %><br />
    <%= f.number_field :old_grade %>
  </div>
  <div class="field">
    <%= f.label :new_grade %><br />
    <%= f.number_field :new_grade %>
  </div>
  <div class="field">
    <%= f.label :new_part_id %><br />
    <%= f.number_field :new_part_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maintenance_issues/edit.html.erb
<h1>Editing maintenance_issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @maintenance_issue %> |
<%= link_to 'Back', maintenance_issues_path %>

app/views/maintenance_issues/index.html.erb
<h1>Listing maintenance_issues</h1>

<table>
  <tr>
    <th>Maintenance</th>
    <th>Part</th>
    <th>Fixed</th>
    <th>Old grade</th>
    <th>New grade</th>
    <th>New part</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maintenance_issues.each do |maintenance_issue| %>
  <tr>
    <td><%= maintenance_issue.maintenance_id %></td>
    <td><%= maintenance_issue.part_id %></td>
    <td><%= maintenance_issue.fixed %></td>
    <td><%= maintenance_issue.old_grade %></td>
    <td><%= maintenance_issue.new_grade %></td>
    <td><%= maintenance_issue.new_part_id %></td>
    <td><%= link_to 'Show', maintenance_issue %></td>
    <td><%= link_to 'Edit', edit_maintenance_issue_path(maintenance_issue) %></td>
    <td><%= link_to 'Destroy', maintenance_issue, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Maintenance issue', new_maintenance_issue_path %>

app/views/maintenance_issues/new.html.erb
<h1>New maintenance_issue</h1>

<%= render 'form' %>

<%= link_to 'Back', maintenance_issues_path %>

app/views/maintenance_issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Maintenance:</b>
  <%= @maintenance_issue.maintenance_id %>
</p>

<p>
  <b>Part:</b>
  <%= @maintenance_issue.part_id %>
</p>

<p>
  <b>Fixed:</b>
  <%= @maintenance_issue.fixed %>
</p>

<p>
  <b>Old grade:</b>
  <%= @maintenance_issue.old_grade %>
</p>

<p>
  <b>New grade:</b>
  <%= @maintenance_issue.new_grade %>
</p>

<p>
  <b>New part:</b>
  <%= @maintenance_issue.new_part_id %>
</p>


<%= link_to 'Edit', edit_maintenance_issue_path(@maintenance_issue) %> |
<%= link_to 'Back', maintenance_issues_path %>